# Generated by Django 2.1.5 on 2023-04-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universityclasses',
            options={'verbose_name_plural': 'University Classes'},
        ),
    ]
